
scene:
  buffer_frames: 1-90
  force_update: false
  render_output: 'imgs/buffer/'
  engine: CYCLES # todo: figure out how to do EEVEE
  blend_file: scene.blend
  render_format: PNG
  blender_flags: ''

edit:
  buffer_frames: 1-90
  force_update: false
  render_output: 'imgs/out/'
  engine: CYCLES
  blend_file: edit.blend
  render_format: AVIRAW
  blender_flags: '-a' # include this to render as a video

cool_scene:
  buffer_frames: 1-90
  force_update: false
  render_output: 'imgs/buffer/'
  engine: CYCLES # todo: figure out how to do EEVEE
  blend_file: cool_scene.blend
  render_format: PNG
  blender_flags: ''

file_output_format: '{bfile}_{stage}_####'
docker:
  image: tennisgazelle/blender-pipeline:latest
  #render_cmd: docker run --rm -v {cwd}/blender/:/blender/ -v {cwd}/imgs:/imgs ikester/blender blender/{blend_file} -o {output_location} -E {engine} -F {format} -t 8 {flags}
  render_cmd: docker run --rm -v {cwd}/blender/:/blender/ -v {cwd}/imgs:/imgs tennisgazelle/blender-pipeline:latest blender/{blend_file} -E {engine} -F {format} -t 8 {flags}
  python_cmd: docker run --rm -v ${cwd}/blender/:/blender/ -v ${cwd}/scripts:/scripts -v ${cwd}/config.yaml:/config.yaml tennisgazelle/blender-pipeline:latest blender/scene.blend --python scripts/get_path.py
  var_defaults:
    engine: CYCLES
    format: PNG
    output_location: imgs/buffer/

