name: PR Render

on:
  # allows for manual triggering from github
  workflow_dispatch:
  pull_request:
    paths:
      - 'blender/**'


jobs:
  Scene-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Building Docker image
        run: docker build -t blender-pipeline:latest scripts/

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          make set_paths
          make scene_render

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scene-buffer-files
          path: imgs/buffer/
