name: PR Render

on: [ pull_request ]

  # allows for manual triggering from github
  workflow_dispatch:

jobs:
  Scene-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          # make scene_render
          scripts/render.py --stage=scene

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scene-buffer-files
          path: imgs/buffer/
