name: Full Render

on:
  push:
    branches: [ $default-branch ]

jobs:
  full-render:
    runs-on: ikester/blender

    steps:
      - uses: actions/checkout@v2
      - name: Create Raw Render from Scene
        run: make scene_render
      - name: Create Composite Render
        run: make edit_render