name: Full Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allows for manual triggering from github
  workflow_dispatch:

jobs:
  full-render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          make scene_render

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scene-buffer-files
          path: imgs/buffer/scene_frame*.png

      - name: Create Composite Render
        run: |
          echo "Creating composited avi"
          make edit_render

      - name: Upload Completed Movie
        uses: actions/upload-artifact@v1
        with:
          name: output-render-file
          path: imgs/out/*