name: Full Render

on:
  # allows for manual triggering from github
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'blender/**'
      - 'scripts/**'
      - 'imgs/**'


jobs:
  Scene-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_PASS }}

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
        with:
          path: scripts/requirements.txt

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          make scene_render

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scene-buffer-files
          path: imgs/buffer/

  Final-Render:
    needs: Scene-Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_PASS }}

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
        with:
          path: scripts/requirements.txt
          
      - uses: actions/download-artifact@v2
        with:
          path: imgs/buffer/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Composite Render
        run: |
          echo "Creating composited avi"
          make edit_render

      - name: Upload Completed Movie
        uses: actions/upload-artifact@v1
        with:
          name: output-render-file
          path: imgs/out/
