name: Full Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allows for manual triggering from github
  workflow_dispatch:

jobs:
  full-render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          make scene_render

      - name: Create Composite Render
        run: |
          echo "Creating composited avi"
          make edit_render
